name: CI

on: 
  push:
    branchs:
  pull_request:

jobs: 
  build:
    runs-on: ubuntu-latest
    steps:

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'

      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Download dependencies
        run: composer update --no-interaction --no-progress 
      

      - uses: isbang/compose-action@v1.5.1
        with:
          compose-file: "./docker-compose.yml"
          down-flags: "--volumes"
          services: |
            php
            selenium

      - name: Sleep to wait for Selenium
        shell: bash
        run: |
          sleep 30 &

      - name: Run tests
        run: ./vendor/bin/pest